import '@/styles/globals.css';
import { Inter } from 'next/font/google';
import { Footer } from '@/components/Footer';
import { NavBar } from '@/components/NavBar';
import { ThemeProvider } from '@/context/ThemeContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <section className="container">
            <NavBar />
            {children}
            <Footer />
          </section>
        </ThemeProvider>
      </body>
    </html>
  );
}
